-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 15:11:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT UNIQUE,
  `Nom` VARCHAR(45) NOT NULL,
  `Prénom` VARCHAR(45) NOT NULL,
  `NumeroTelephone` INT NOT NULL,
  `MotDePasse` VARCHAR(45) NULL,
  `Ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Logement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Logement` (
  `idLogement` INT UNIQUE,
  `Ville` VARCHAR(45) NULL,
  `Taille` INT NULL,
  `Type` VARCHAR(45) NULL,
  `AnneeDeCreation` DATETIME NULL,
  `Adresse` VARCHAR(45) NULL,
  `Photo` VARCHAR(45) NULL,
  `Description` VARCHAR(245) NULL,
  PRIMARY KEY (`idLogement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Annonce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Annonce` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Annonce` (
  `idAnnonce` INT UNIQUE,
  `Logement` INT NOT NULL,
  `Utilisateur` INT NOT NULL,
  `Prix` INT NULL,
  PRIMARY KEY (`idAnnonce`),
  CONSTRAINT `fk_Annonce_Logement`
    FOREIGN KEY (`Logement`)
    REFERENCES `mydb`.`Logement` (`idLogement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Annonce_Utilisateur1`
    FOREIGN KEY (`Utilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Offre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Offre` (
  `idOffre` INT UNIQUE,
  `Annonce` INT NOT NULL,
  `Logement` INT NOT NULL,
  `Vendeur` INT NOT NULL,
  `Acheteur` INT NOT NULL,
  `DateCreation` DATETIME NOT NULL,
  PRIMARY KEY (`idOffre`),
  CONSTRAINT `fk_Offre_Annonce1`
    FOREIGN KEY (`Annonce`)
    REFERENCES `mydb`.`Annonce` (`idAnnonce`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Offre_Logement1`
    FOREIGN KEY (`Logement`)
    REFERENCES `mydb`.`Logement` (`idLogement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Offre_Utilisateur1`
    FOREIGN KEY (`Vendeur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Offre_Utilisateur2`
    FOREIGN KEY (`Acheteur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
